require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - '**/node_modules/**/*'
    - 'db/schema.rb'
    - 'bin/*'

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'

RSpec/ContextWording:
  Enabled: false

RSpec/InstanceVariable:
  AssignmentOnly: true

RSpec/NestedGroups:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StructInheritance:
  Exclude:
    - 'app/policies/**/*'
